/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDecapCallbackRouteImport } from './routes/api/decap/callback'
import { Route as ApiDecapAuthRouteImport } from './routes/api/decap/auth'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecapCallbackRoute = ApiDecapCallbackRouteImport.update({
  id: '/api/decap/callback',
  path: '/api/decap/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecapAuthRoute = ApiDecapAuthRouteImport.update({
  id: '/api/decap/auth',
  path: '/api/decap/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/decap/auth': typeof ApiDecapAuthRoute
  '/api/decap/callback': typeof ApiDecapCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/decap/auth': typeof ApiDecapAuthRoute
  '/api/decap/callback': typeof ApiDecapCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/decap/auth': typeof ApiDecapAuthRoute
  '/api/decap/callback': typeof ApiDecapCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/api/decap/auth' | '/api/decap/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/api/decap/auth' | '/api/decap/callback'
  id: '__root__' | '/' | '/admin' | '/api/decap/auth' | '/api/decap/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiDecapAuthRoute: typeof ApiDecapAuthRoute
  ApiDecapCallbackRoute: typeof ApiDecapCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decap/callback': {
      id: '/api/decap/callback'
      path: '/api/decap/callback'
      fullPath: '/api/decap/callback'
      preLoaderRoute: typeof ApiDecapCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decap/auth': {
      id: '/api/decap/auth'
      path: '/api/decap/auth'
      fullPath: '/api/decap/auth'
      preLoaderRoute: typeof ApiDecapAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiDecapAuthRoute: ApiDecapAuthRoute,
  ApiDecapCallbackRoute: ApiDecapCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
